TP sur la bibliothèque NumPy

Introduction

NumPy est une bibliothèque Python essentielle pour le calcul numérique. Elle permet de manipuler des tableaux multidimensionnels (arrays) et fournit des fonctions pour effectuer des opérations mathématiques, statistiques et logiques. NumPy est largement utilisé en science des données, en calcul scientifique et en analyse numérique.

Dans ce TP, nous allons explorer :

L'installation et l'importation de NumPy
La création de tableaux
Les opérations sur les tableaux
L'indexation et le slicing
Les fonctions statistiques et mathématiques
La manipulation de formes
Quelques applications avancées

Partie 1 : Installation et importation de NumPy

Installation

Pour installer NumPy, ouvrez un terminal ou une invite de commande et exécutez :

pip install numpy

Importation

Une fois installée, importez NumPy dans votre script Python avec :

In [1]:
import numpy as np #L'alias np est une convention courante pour simplifier l'utilisation.

Partie 2 : Création de tableaux (arrays)

Les tableaux NumPy sont similaires aux listes Python, mais optimisés pour les calculs numériques.

Tableaux 1D et 2D

In [2]:
arr_1d = np.array([1, 2, 3, 4]) # Création d'un tableau 1D avec des entiers
arr_2d = np.array([[1, 2], [3, 4]]) # Création d'un tableau 2D avec des entiers
print(arr_1d)
print(arr_2d) # Affichage des tableaux
print(arr_1d.shape) # Affichage de la forme du tableau 1D
print(arr_2d.shape) # Affichage de la forme du tableau 2D

[1 2 3 4]
[[1 2]
 [3 4]]
(4,)
(2, 2)


Fonctions pour créer des tableaux spéciaux

NumPy propose des fonctions utiles :

np.zeros(shape) : Crée un tableau rempli de zéros.

np.ones(shape) : Crée un tableau rempli de uns.

np.eye(N) : Crée une matrice identité de taille N.

np.arange(start, stop, step) : Crée une séquence de nombres.

np.linspace(start, stop, num) : Crée num valeurs espacées uniformément.

In [3]:
zeros = np.zeros((2, 3))  # Tableau 2x3 de zéros
print(zeros)

ones = np.ones((3, 2))    # Tableau 3x2 de uns
print(ones)

identity = np.eye(3)      # Matrice identité 3x3
print(identity)

seq = np.arange(0, 10, 2) # Tableau de 0 à 10 avec un pas de 2
print(seq)

lin = np.linspace(0, 1, 5) # Tableau de 5 valeurs entre 0 et 1
print(lin)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]
[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[0 2 4 6 8]
[0.   0.25 0.5  0.75 1.  ]


Partie 3 : Opérations sur les tableaux

Opérations élémentaires

NumPy permet des calculs élément par élément sur les tableaux :

In [4]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

print(a + b)  
print(a - b)  
print(a * b)  
print(a / b)  

[5 7 9]
[-3 -3 -3]
[ 4 10 18]
[0.25 0.4  0.5 ]


Produit matriciel

Pour les tableaux 2D, utilisez np.dot() ou l'opérateur @ :

In [5]:
mat1 = np.array([[1, 2], [3, 4]])
mat2 = np.array([[5, 6], [7, 8]])
print(np.dot(mat1, mat2))

[[19 22]
 [43 50]]


Fonctions universelles (ufuncs)

Appliquez des fonctions mathématiques à chaque élément :

In [12]:
arr = np.array([0, np.pi/2, np.pi])
print(np.sin(arr))
print(np.cos(arr))
print(np.tan(arr))

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


Partie 4 : Indexation et slicing

Indexation

Accédez aux éléments avec des indices :

In [7]:
arr = np.array([10, 20, 30, 40])
print(arr[0])   
print(arr[1])

mat = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(mat[1, 2])  # Élément à la 2ème ligne et 3ème colonne
print(mat[0, :]) # Première ligne
print(mat[:, 1]) # Deuxième colonne
print(mat[1:3, 0:2]) # Sous-matrice de la 2ème à la 3ème ligne et de la 1ère à la 2ème colonne
print(mat[::2, ::2]) # Sous-matrice avec un pas de 2
print(mat[1, 1:3]) # Élément à la 2ème ligne et colonnes 2 à 3

10
20
6
[1 2 3]
[2 5 8]
[[4 5]
 [7 8]]
[[1 3]
 [7 9]]
[5 6]


Partie 5 : Fonctions statistiques et mathématiques

NumPy fournit des outils pour analyser les données :

np.mean() : Moyenne

np.median() : Médiane

np.std() : Écart-type

np.sum() : Somme

np.min() : Minimum

np.max() : Maximum

In [8]:
data = np.array([1, 2, 3, 4, 5])
print(np.mean(data)) # Moyenne 
print(np.sum(data))   # Somme
print(np.std(data))   # Écart type
print(np.max(data))  # Maximum
print(np.min(data))  # Minimum
print(np.median(data)) # Médiane

3.0
15
1.4142135623730951
5
1
3.0


Calculs par axe

Pour les tableaux 2D, spécifiez l'axe :

In [9]:
mat = np.array([[1, 2], [3, 4]])
print(np.sum(mat, axis=0))  # Somme par colonne
print(np.sum(mat, axis=1)) # Somme par ligne
print(np.mean(mat, axis=0)) # Moyenne par colonne
print(np.mean(mat, axis=1)) # Moyenne par ligne

[4 6]
[3 7]
[2. 3.]
[1.5 3.5]


Partie 6 : Manipulation de formes

In [10]:
arr = np.arange(6)  # Tableau de 0 à 5
mat = arr.reshape((2, 3))  # Reshape en 2 lignes et 3 colonnes
print(mat) # Affiche le tableau
print(mat.T) # Transposition de la matrice
print(mat.flatten()) # Aplatir la matrice en un tableau 1D
print(mat.ravel()) # Aplatir la matrice en un tableau 1D (vue)


[[0 1 2]
 [3 4 5]]
[[0 3]
 [1 4]
 [2 5]]
[0 1 2 3 4 5]
[0 1 2 3 4 5]


Génération de nombres aléatoires

Utilisez np.random pour générer des données aléatoires :

In [11]:
rand_arr = np.random.rand(5)  # 5 nombres entre 0 et 1
print(rand_arr)

rand_mat = np.random.randn(2, 2)  # Matrice 2x2 (distribution normale)
print(rand_mat)

rand_int = np.random.randint(0, 10, (2, 3))  # Matrice 2x3 d'entiers entre 0 et 10
print(rand_int)


[0.44528803 0.6208392  0.40406291 0.35121243 0.40062323]
[[-0.84926935  0.46464429]
 [ 0.42512009  1.52125501]]
[[0 6 2]
 [8 4 5]]
